import { Button, Typography } from '@mui/material';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen flex flex-col items-center'>
        <Typography variant='h1' className='pt-5 pb-10'>Profile</Typography>
        <section className='flex flex-col items-center'>
          <Button href='/availability' variant='contained' disableElevation className="bg-teal hover:bg-white border border-solid hover:border-teal text-white hover:text-teal">Availability</Button>
          <Button href='/calendarshow' variant='contained' disableElevation className="bg-teal hover:bg-white border border-solid hover:border-teal text-white hover:text-teal">Show Calendar</Button>
        </section>
      </main>
    </>
  )
};
